import { readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig } from 'vite';

// No framework plugin: the site is static HTML + one plain script.
// Vite is here for content-hashed asset output and the dev server.
//
// services/*.html are generated by scripts/build-pages.mjs (npm prebuild),
// so this glob runs after they exist.
const serviceDir = resolve(__dirname, 'services');
const servicePages = Object.fromEntries(
  readdirSync(serviceDir)
    .filter((f) => f.endsWith('.html'))
    .map((f) => [`services/${f.replace(/\.html$/, '')}`, resolve(serviceDir, f)])
);

export default defineConfig({
  appType: 'mpa',
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        ...servicePages,
      },
    },
  },
  server: {
    port: 8081,
    host: true,
    allowedHosts: true,
  },
});
